[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed  = 115200
upload_speed   = 921600

lib_ldf_mode   = chain
lib_compat_mode = strict

lib_deps =
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    bblanchon/ArduinoJson @ ^7.0.0
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    olikraus/U8g2 @ ^2.35.19

build_flags =
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
    -D CONFIG_ASYNC_TCP_STACK_SIZE=4096